app/__init__.py
from flask import Flask
from .routes import routes
# from .models import db

def create_app():
    app = Flask(__name__)
    app.config.from_object('config.Config')
    
    # db.init_app(app)

    app.register_blueprint(routes.routes, url_prefix="/")
    
    return app

app/routes/routes.py
from flask import Blueprint, render_template

routes = Blueprint("routes",__name__)

@routes.route("/",methods = ["GET","POST"])
def index():
    return render_template('index.html')

@routes.route("/projects", methods=["GET","POST"])
def projects():
    return render_template('projects.html')

@routes.route("/contact", methods=["GET","PUSH"])
def  contact():
    return render_template('contact.html')

app/templates/contact.html
{% extends "layout.html" %}
{% block head %}
    <title>CONTACT</title>
    <link rel="stylesheet" href="../static/styles/contact.css">
{% endblock  %}
{% block body %}
    <div class="mainContainer">
        <div class="mainContent">
            <div class="contactPerson">
                <div class="contactPersonTitle">
                    <h3>CONTACT</h3>
                </div>
                <div class="contactPersonDesc">
                    <p>
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </p>
                </div>
                <div class="contactPersonSub">
                    <ul>
                        <li>
                            <h4>Address</h4>
                            <p>Jln.ABC Rt/Rw:xx/xx Kel.xxxxxx Kec.xxxxx</p>
                        </li>
                        <li>
                            <h4>Phone</h4>
                            <p>(+62) xxx-xxxx-xxxx</p>
                        </li>
                        <li>
                            <h4>E-mail</h4>
                            <p>namasaya@gmail.com</p>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="contactForm">
                <div class="contactPersonTitle">
                    <h3>CONTACT <span>  </span> FORM</h3>
                </div>
                <div class="contactForms">
                    <div class="formItem">
                        <label for="">Your Name</label>
                        <input type="text" required>
                    </div>
                    <div class="formItem">
                        <label for="">Your Phone</label>
                        <input type="number" name="" id="">
                    </div>
                    <div class="formItem">
                        <label for="">Your Email</label>
                        <input type="email">
                    </div>
                    <div class="formItem">
                        <label for="">Message</label>
                        <input type="text">
                    </div>
                    <div class="btnSubmit">
                        <a href="#">
                            <button type="submit">SEND MESSAGE</button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock  %}
{% block javascript %}{% endblock  %}

app/templates/index.html
{% extends "layout.html" %}
{% block head %}
    <title>PORTOFOLIO</title>
    <link rel="stylesheet" href="../static/styles/index.css">
{% endblock  %}
{% block body %}
        <div class="mainContainer">
            <div class="mainContent">
                <div class="mainText">
                    <p class="text_leftSide">
                        I AM 
                    </p>
                    <p>
                        <span class="my_name">FARIS</span>
                    </p>
                    <p class="text_rightSide">
                        A <span class="auto-type"></span>
                    </p>
                </div>
            </div>
        </div>            
{% endblock  %}

{% block javascript %}
<script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.12"></script>
<script src="../static/javascript/index.js"></script>
{% endblock  %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://unicons.iconscout.com/release/v4.0.8/css/line.css">
    
    <link rel="icon" href="../static/img/logo.png" type="image/x-icon">
    <link rel="stylesheet" href="../static/styles/stylesLayout.css">
    <link rel="stylesheet" href="../static/styles/stylesNavbar.css">

    {% block head %}{% endblock  %}
</head>
<body>
    {% include "navbar.html" %}
    <div class="containerIndex">
        <div class="sosmedContainer">
            <div class="sosmedContent">
                <ul>
                    <li>
                        <a href="">
                            <i class="uil uil-instagram-alt"></i>
                        </a>
                    </li>
                    <li>
                        <a href="">
                            <i class="uil uil-twitter"></i>
                        </a>
                    </li>                   
                    <li>
                        <a href="">
                            <i class="uil uil-telegram"></i>
                        </a>
                    </li>
                </ul>
            </div>
        </div>        
        {% block body %}{% endblock  %}
        <div class="navContainer">
            <div class="navContent">
                <a href="#" id="up">
                    <i class="uil uil-angle-double-up"></i>
                </a>
                <p class="text_vertically" id="text">
                   PORTOFOLIO
                </p>
                <a href="#" id="bottom">
                    <i class="uil uil-angle-double-down"></i>
                </a>
            </div>
        </div>
    </div>

    {% block javascript %}{% endblock  %}
    <script src="../static/javascript/navigation.js"></script>
</body>
</html>

app/templates/navbar.html
<div class="nav">
    <div class="items">
        <a href="/" class="logo">
            <h3>FARIS</h3>
            <!-- <img src="../static/img/logo.png" alt=""> -->
        </a>
        <div class="menu right-align">
            <ul>
                <li>
                    <a href="{{ url_for('routes.projects') }}">PROJECTS</a>
                </li>
                <li>
                    <a href="{{ url_for('routes.contact') }}">CONTACT</a>
                </li>
            </ul>
        </div>
    </div>
</div>

app/templates/projects.html
{% extends "layout.html" %}
{% block head %}
    <title>PROJECTS</title>
    <link rel="stylesheet" href="../static/styles/projects.css">
{% endblock  %}
{% block body %}
    <div class="mainContainer">
        <div class="mainContent">
            <div class="projectsPreview">
                <div class="projectsImage">
                    <img src="../static/img/projects/newsCapture.png" alt="">
                </div>
            </div>                
            <div class="projectsContent">
                <div class="projectsTitle">
                    NEWS
                </div>
                <div class="projectsDescription">
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                </div>                    
            </div>
            <div class="btnViewProjects">
                <a href="">
                    <button type="submit">VIEW PROJECTS</button>
                </a>
            </div>
        </div>
    </div>
{% endblock  %}
{% block javascript %}{% endblock  %}